### ISSUE TITLE
代码运行后最终结果与描述不符

### ISSUE THREAD

**Issue by Dakai798** [Xuanfang1121/CRASpell_pytorch#3]
正常搭建环境，下载预训练模型，运行train.py之后出现结果数值全是0：
2023-05-17 21:46:05,776 - INFO - train.py:44 - train() - data add noise
2023-05-17 21:46:05,776 - INFO - train.py:45 - train() - train data size:281381
2023-05-17 21:46:05,996 - INFO - train.py:57 - train() - data add noise
2023-05-17 21:46:05,996 - INFO - train.py:58 - train() - test merr size:242
2023-05-17 21:46:06,330 - INFO - train.py:70 - train() - test data size:1062
2023-05-17 21:46:06,331 - INFO - train.py:75 - train() - train data pre epoch number:140691
2023-05-17 21:46:12,858 - INFO - train.py:128 - train() - multi-error result
2023-05-17 21:47:34,402 - INFO - util.py:302 - score_f() - token num: gold_n:281, pred_n:0, right_n:0
2023-05-17 21:47:34,403 - INFO - util.py:303 - score_f() - token check: p=0.000, r=0.000, f=0.000
2023-05-17 21:47:34,403 - INFO - util.py:313 - score_f() - token correction-1: p=0.000, r=0.000, f=0.000
2023-05-17 21:47:34,403 - INFO - util.py:314 - score_f() - token correction-2: p=0.000, r=0.000, f=0.000
2023-05-17 21:47:34,403 - INFO - util.py:266 - model_evaluate() - precision:0.0, recall:0.0, f1_score:0.0
2023-05-17 21:47:34,405 - INFO - train.py:130 - train() - test data result

**Comment by Learner-feng** [comment]
同样如此

**Comment by Dakai798** [comment]
@

**Comment by Dakai798** [comment]
@Xuanfang1121

**Comment by Learner-feng** [comment]
> @

您好，我想问下您解决了吗

**Comment by Dakai798** [comment]
没有，请问你那边有头绪嘛？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Learner-feng ***@***.***&gt;
发送时间: 2023年5月28日 21:34
收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&gt;
抄送: Dakai798 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3)





  
@
  
您好，我想问下您解决了吗

**Comment by Learner-feng** [comment]
暂时没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月28日(周日) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3)




 没有，请问你那边有头绪嘛？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: Learner-feng ***@***.***&amp;gt; 
 发送时间: 2023年5月28日 21:34 
 收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&amp;gt; 
 抄送: Dakai798 ***@***.***&amp;gt;, State change ***@***.***&amp;gt; 
 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 
 
 
 
 
 
    
 @ 
    
 您好，我想问下您解决了吗

**Comment by shirain-he** [comment]
> 没有，请问你那边有头绪嘛？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Learner-feng ***@***.***&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&gt; 抄送: Dakai798 ***@***.***&gt;, State change ***@***.***&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

怎么样？现在有头绪吗？哈哈哈

**Comment by Learner-feng** [comment]
就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xuanfang1121/CRASpell_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3)





  
没有，请问你那边有头绪嘛？ 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
怎么样？现在有头绪吗？哈哈哈

**Comment by Dakai798** [comment]
不好意思，请问具体是哪一块代码能方便截下图嘛？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Learner-feng ***@***.***&gt;
发送时间: 2023年10月10日 19:07
收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&gt;
抄送: Dakai798 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3)





 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Xuanfang1121/CRASpell_pytorch"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年10月10日(星期二) 晚上6:40 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 
 
 
 
 
 
    
 没有，请问你那边有头绪嘛？ 发自我的iPhone 
  … 
  ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&amp;gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&amp;gt; 抄送: Dakai798 @.&amp;gt;, State change @.&amp;gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&amp;gt; 
    
 怎么样？现在有头绪吗？哈哈哈

**Comment by shirain-he** [comment]
> 不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Learner-feng ***@***.***&gt; 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&gt; 抄送: Dakai798 ***@***.***&gt;, State change ***@***.***&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2023年10月10日(星期二) 晚上6:40 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&amp;gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&amp;gt; 抄送: Dakai798 @.&amp;gt;, State change @.&amp;gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&amp;gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

那位朋友说的应该是src/utils/util.py里面的score_f函数，这块是具体的指标计算。我正在读代码，看能不能发现问题

**Comment by shirain-he** [comment]
> 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

老哥，是utils.py里面的escore_f那块计算的问题吗？刚接触这块的东西

**Comment by shirain-he** [comment]
> 不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Learner-feng ***@***.***&gt; 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch ***@***.***&gt; 抄送: Dakai798 ***@***.***&gt;, State change ***@***.***&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2023年10月10日(星期二) 晚上6:40 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&amp;gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&amp;gt; 抄送: Dakai798 @.&amp;gt;, State change @.&amp;gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&amp;gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&amp;gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;
经过我的测试，好像是预训练权重没加载进去导致的，我换了一个bert-base-chinese的权重来初始化
，就行了，我看了原作者和这个仓库的指标代码，基本是一模一样的。

**Comment by Dakai798** [comment]
> > 不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Learner-feng _**@**_._**> 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch _**@**_.**_> 抄送: Dakai798 _**@**_._**>, State change _**@**_.**_> 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> > ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" _**@**_._**&gt;; 发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40 _**@**_.**_&gt;; _**@**_._**_**@**_.**_&gt;; 主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @._**&gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > 经过我的测试，好像是预训练权重没加载进去导致的，我换了一个bert-base-chinese的权重来初始化
> > ，就行了，我看了原作者和这个仓库的指标代码，基本是一模一样的。

您好，请问你后来换成哪个预训练模型成功了？方便说明一下吗？

**Comment by Dakai798** [comment]
> 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

您好，请问可以发出来修改后的代码嘛？这边实验结果还是全零

**Comment by shirain-he** [comment]
> > > 不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: Learner-feng _**@**_._**> 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch _**@**_.**_> 抄送: Dakai798 _**@**_._**>, State change _**@**_.**_> 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
> > > ------------------ 原始邮件 ------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" _**@**_._**>; 发送时间: 2023年10月10日(星期二) 晚上6:40 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.> 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.> 抄送: Dakai798 @.>, State change @.> 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @._**> 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.**_> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> > > 经过我的测试，好像是预训练权重没加载进去导致的，我换了一个bert-base-chinese的权重来初始化
> > > ，就行了，我看了原作者和这个仓库的指标代码，基本是一模一样的。
> 
> 您好，请问你后来换成哪个预训练模型成功了？方便说明一下吗？

我随便找了个bert-base-chinese
https://huggingface.co/bert-base-chinese

**Comment by shirain-he** [comment]
我这边利用transformrs包的来将原文中cbert转成torch格式，但是转换完成后无法加载进去，希望有好的tensorflow权重转torch权重方法，这样就可以用torch复现了

**Comment by Dakai798** [comment]
我也是加载的这个模型，可结果还是0


&nbsp;


大凯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月15日(星期天) 下午3:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3)





    
不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch _@**._&gt; 抄送: Dakai798 ***@***.***&gt;, State change @._&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40 @._&gt;; ***@***.***@.&gt;; 主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @._&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _@_.*&gt;
 经过我的测试，好像是预训练权重没加载进去导致的，我换了一个bert-base-chinese的权重来初始化
 ，就行了，我看了原作者和这个仓库的指标代码，基本是一模一样的。
   
您好，请问你后来换成哪个预训练模型成功了？方便说明一下吗？
  
我随便找了个bert-base-chinese
 https://huggingface.co/bert-base-chinese

**Comment by shirain-he** [comment]
> 我也是加载的这个模型，可结果还是0 &nbsp; 大凯 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月15日(星期天) 下午3:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; "State ***@***.***&gt;; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 不好意思，请问具体是哪一块代码能方便截下图嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年10月10日 19:07 收件人: Xuanfang1121/CRASpell_pytorch _@**._&gt; 抄送: Dakai798 ***@***.***&gt;, State change @._&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 就是评级指标写错了，我改成我之前写的评价指标代码就正常了。你改下评价指标那块的代码。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Xuanfang1121/CRASpell_pytorch" ***@***.***&gt;; 发送时间:&nbsp;2023年10月10日(星期二) 晚上6:40 @._&gt;; ***@***.***@.&gt;; 主题:&nbsp;Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) 没有，请问你那边有头绪嘛？ 发自我的iPhone … ------------------ 原始邮件 ------------------ 发件人: Learner-feng @.&gt; 发送时间: 2023年5月28日 21:34 收件人: Xuanfang1121/CRASpell_pytorch @.&gt; 抄送: Dakai798 @.&gt;, State change @.&gt; 主题: Re: [Xuanfang1121/CRASpell_pytorch] 代码运行后最终结果与描述不符 (Issue #3) @ 您好，我想问下您解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 怎么样？现在有头绪吗？哈哈哈 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @._&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _@_.*&gt; 经过我的测试，好像是预训练权重没加载进去导致的，我换了一个bert-base-chinese的权重来初始化 ，就行了，我看了原作者和这个仓库的指标代码，基本是一模一样的。 您好，请问你后来换成哪个预训练模型成功了？方便说明一下吗？ 我随便找了个bert-base-chinese https://huggingface.co/bert-base-chinese — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你要跑一个epoch后再看，他评估集用的是sighan15_test和sighan_multierro_test,你可以看下这两个文本，基本前100个序列都是完全正确的，所以刚开始指标的分子：即检测到错误是0个，所以指标肯定是0
